import { Generated } from 'kysely';

// Users table representation mapped from migrations/V2__users_table.sql
export interface UserTable {
  id: Generated<string>; // uuid, default generated by DB
  username: string;
  email: string;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null; // soft delete marker
}
